### ISSUE TITLE
M_PI not defined in matrix.c

### ISSUE THREAD

**Issue by octogurnik** [gustavopezzi/3dengine#1]
I just tried to compile the project and get this error here:

```
./src/matrix.c: In function ‘mat4_make_perspective’:
./src/matrix.c:109:59: error: ‘M_PI’ undeclared (first use in this function); did you mean ‘__P’?
     float fov_scale = 1 / tan((fov_degrees / 2) / 180.0 * M_PI);
                                                           ^~~~
```

I solved it writing this line in `matrix.c` :
```
#define M_PI 3.14
```

**Comment by gustavopezzi** [comment]
I was trying to avoid defining it manually, since it should be defined in math.h. But I guess this is only defined in POSIX. I will improve it and make this portable. Thanks for the heads up!

**Comment by octogurnik** [comment]
You are welcome!
I just found this post about `math.h` : https://stackoverflow.com/questions/5007925/using-m-pi-with-c89-standard

**Comment by gustavopezzi** [comment]
Can I just ask you what compiler you're using?

**Comment by octogurnik** [comment]
No problem:
GNU C compiler
Version: 4:7.4.0-1ubuntu2.3

Im using Linux Mint, It's the native compiler for C I guess

**Comment by gustavopezzi** [comment]
I see. I'm surprised, I was under the impression that gcc would be ok with it. I am using clang, but I will definitely fix this before the course goes out. Thanks again!
